# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attend_Recodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(max_length=50)),
                ('group_id', models.IntegerField()),
                ('time', models.IntegerField()),
                ('lecture_or_tutorial', models.BooleanField(default=True)),
                ('owner', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(blank=True, null=True, upload_to='')),
                ('time', models.IntegerField()),
                ('data', models.CharField(max_length=5120)),
            ],
        ),
        migrations.AddField(
            model_name='attend_recodes',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attend_server.Attendance'),
        ),
    ]
