# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attend_server', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Module',
            new_name='Student',
        ),
    ]
