# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 04:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attend_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial_Group_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attend_server.Modules')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attend_server.Student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
