# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attend_server', '0002_auto_20160727_2015'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set([('name', 'module')]),
        ),
    ]
