# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_tech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='feature',
            field=models.CharField(max_length=10240),
        ),
    ]
