# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 12:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend_server', '0003_auto_20160727_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$')]),
        ),
    ]
